version: 2
jobs:
  latest:
    environment:
      CC_TEST_REPORTER_ID: 7e6c6740d17509f50ec9c750311962b3b3fcb2d3a7033c2f664dc3b012bd9439
    docker:
      - image: circleci/ruby:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: ruby version
          command: ruby --version
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run: gem install bundler
      - restore_cache:
          keys:
            - v1-gems-latest-{{ .Branch }}-{{ .Revision }}
            - v1-gems-latest-{{ .Branch }}
            - v1-gems-latest-
      - run:
          name: install gems
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle-latest
      - save_cache:
          key: v1-gems-latest-{{ .Branch }}-{{ .Revision }}
          paths:
            - ./vendor/bundle-latest
      - run:
          name: Run Specs
          command: bundle exec rspec spec/**/*.rb
      - run:
          name: Report Coverage
          command: |
            ./cc-test-reporter format-coverage -t simplecov $CIRCLE_ARTIFACTS/coverage/.resultset.json
            ./cc-test-reporter upload-coverage
      - store_artifacts:
          path: coverage/coverage.json
  build_2_6:
    docker:
      - image: circleci/ruby:2.6
    working_directory: ~/repo
    steps:
      - checkout
      - run: gem install bundler
      - restore_cache:
          keys:
            - v1-gems-build_2_6-{{ .Branch }}-{{ .Revision }}
            - v1-gems-build_2_6-{{ .Branch }}
            - v1-gems-build_2_6-
      - run:
          name: install gems
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle-2_5
      - save_cache:
          key: v1-gems-build_2_6-{{ .Branch }}-{{ .Revision }}
          paths:
            - ./vendor/bundle-2_6
      - run:
          name: Run Specs
          command: bundle exec rspec spec/**/*.rb
  build_2_5:
    docker:
      - image: circleci/ruby:2.5
    working_directory: ~/repo
    steps:
      - checkout
      - run: gem install bundler
      - restore_cache:
          keys:
            - v1-gems-build_2_5-{{ .Branch }}-{{ .Revision }}
            - v1-gems-build_2_5-{{ .Branch }}
            - v1-gems-build_2_5-
      - run:
          name: install gems
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle-2_5
      - save_cache:
          key: v1-gems-build_2_5-{{ .Branch }}-{{ .Revision }}
          paths:
            - ./vendor/bundle-2_5
      - run:
          name: Run Specs
          command: bundle exec rspec spec/**/*.rb
workflows:
  version: 2
  specs:
    jobs:
      - build_2_5
      - build_2_6
      - latest
